<a href="https://colab.research.google.com/github/nur303/Problem-solve/blob/main/Lab_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Homework 01:**
Generate random matrix of size 10 x 5. Then, solve the following problems:

<a href="https://colab.research.google.com/github/mirsazzathossain/CSE317-Lab/blob/main/Lab_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

# Set a random seed for reproducibility (optional)
np.random.seed(2)

# Generate a 10x5 matrix with random integers between 1 and 100
matrix = np.random.randint(1, 101, size=(10, 5))

# Print the matrix
print("Random 10x5 Matrix:")
print(matrix)


Random 10x5 Matrix:
[[41 16 73 23 44]
 [83 76  8 35 50]
 [96 76 86 48 64]
 [32 91 21 38 40]
 [68  5 43 52 39]
 [34 59 68 70 89]
 [69 47 71 96 84]
 [32 67 81 53 77]
 [51  5 91 64 80]
 [50 40 47  9 51]]


##### **Problem 01:**
Calculate the sum and mean of the 2nd row of the matrix.

In [29]:
second_row = matrix[1]
row_sum= np.sum(second_row)
row_mean = np.mean(second_row)
print("Second row:", second_row)
print("Sum of 2nd row:", row_sum)
print("Mean of 2nd row:", row_mean)


Second row: [83 76  8 35 50]
Sum of 2nd row: 252
Mean of 2nd row: 50.4


##### **Problem 02:**
Find the sum and mean of all the rows of the matrix.

In [31]:
sum_of_rows=np.sum(matrix,axis=1)
mean_of_rows=np.mean(matrix,axis=1)
print("Sum Of all rpws",sum_of_rows)
print("Mean Of all rpws",mean_of_rows)

Sum Of all rpws [197 252 370 222 207 320 367 310 291 197]
Mean Of all rpws [39.4 50.4 74.  44.4 41.4 64.  73.4 62.  58.2 39.4]


##### **Problem 03:**
Find the mean of the 3rd column of the matrix without using the built-in function and loop.

In [36]:
third_col = matrix[ :, 2]

total = third_col.sum()

mean = total / matrix.shape[0]

print("3rd Column:", third_col)
print("Mean of 3rd column:", mean)


3rd Column: [73  8 86 21 43 68 71 81 91 47]
Mean of 3rd column: 58.9


##### **Problem 04:**
Generate the vector `[25, 16, 9, 4, 1]` and then find the square root of each element of the vector using for loop. **Hint:** Use `np.sqrt()` function to find the square root of a number, don't use any other built-in function.

In [44]:
vector = np.array([25, 16, 9, 4, 1])

sqrt_vector = [ ]

for num in vector:
    a = int(np.sqrt(num))
    sqrt_vector.append(a)

print("Original Vector:", vector)
print("Square Root Vector:", sqrt_vector)


Original Vector: [25 16  9  4  1]
Square Root Vector: [5, 4, 3, 2, 1]


##### **Problem 05:**
Write a function that takes a number and returns a vector like the previous problem. For example, if the input is 5, then the output should be `[25, 16, 9, 4, 1]`. If the input is 10, then the output should be `[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]`.

In [58]:
def squared_vector(num):
    nums = np.arange(num, 0, -1)
    squared_vector = nums ** 2
    return squared_vector

num = int(input('enter a number: '))
result = squared_vector(num)
print(result)

enter a number: 10
[100  81  64  49  36  25  16   9   4   1]


##### **Problem 06:**
Generate the following block matrix:

$$
\begin{bmatrix}
1 & 0 & 0 & 2 & 2 \\
0 & 1 & 0 & 2 & 2 \\
0 & 0 & 1 & 2 & 2 \\
25 & 16 & 9 & 4 & 1 \\
\end{bmatrix}
$$

You can use any built-in function to generate the matrix.

In [59]:
I = np.eye(3, dtype=int)
twos = np.full((3, 2), 2)
top_block = np.hstack((I, twos))
bottom_row = np.array([[25, 16, 9, 4, 1]])
final_matrix = np.vstack((top_block, bottom_row))
print("Block Matrix:")
print(final_matrix)


Block Matrix:
[[ 1  0  0  2  2]
 [ 0  1  0  2  2]
 [ 0  0  1  2  2]
 [25 16  9  4  1]]


##### **Problem 07:**
Plot $y = 2x^2 + 3x + 1$ for $x \in [-3, 3]$ with interval 0.25. You can use any built-in function to plot the graph.

In [ ]:
# Write your code here

##### **Problem 08:**
Plot $x + y + z = 1$ for $x, y \in [-3, 3]$ with interval 0.5. Use meshgrid to generate the grid. You can use any built-in function to plot the surface.

In [ ]:
# Write your code here

##### **Problem 09:**
Download the image of Lena Forsen from the following link: [https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png](https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png). Then, do the following tasks:

*  Load the image to a numpy array.
*  Find the size of the image.
*  Find the minimum and maximum value of the image.
*  Find the mean and standard deviation of the image.
*  Plot the image using `plt.imshow()` or `display()`.
*  Resize the image to 50 x 50.
*  Convert the image to grayscale.
*  Plot the grayscale image using `plt.imshow()` or `display()`.
*  Save the grayscale image using `imsave()`.
*  Stack the columns of the image to form a vector of size 2500 x 1.

In [ ]:
# Write your code here

##### **Problem 10:**
Compute 2nd order Taylor approximation of $e^{2x}$ and $e^{3x}$, and $e^{5x}$ around $a = 0$ for $x \in [-1, 1]$ with interval 0.01. Then, determine which of the following is more accurate:
> 1. Calculating the Taylor approximation separately for each $e^{2x}$, $e^{3x}$ then multiplying them together.
> 2. Calculating the Taylor approximation for $e^{5x}$.

Use mean square error (MSE) to determine the accuracy. Also, plot the Taylor approximation for 1st and 2nd method and the original function in the same plot for visual comparison.

In [ ]:
# Write your code here